# -*- coding: utf-8 -*-
"""emodul_fluida_urbanfarming.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13xMgxJtDwjCCIpoMCFdojUo6Ftb5vlKA

#  E-Modul Fisika: Fluida & Sistem Irigasi Urban Farming
### Untuk Siswa SMA — Kelas XI

---

> **Urban Farming** adalah praktik bercocok tanam di perkotaan — di rooftop, balkon, atau lahan sempit. Agar tanaman tumbuh optimal, dibutuhkan sistem irigasi yang dirancang dengan prinsip **fisika fluida**.

---

## 🎯 Tujuan Pembelajaran
Setelah menyelesaikan e-modul ini, kamu dapat:
1. Menjelaskan konsep tekanan hidrostatis dan penerapannya pada sistem irigasi
2. Menghitung debit air dan kecepatan aliran pada pipa irigasi
3. Menerapkan persamaan kontinuitas dan Bernoulli untuk merancang sistem irigasi sederhana
4. Menganalisis efisiensi sistem irigasi tetes (drip irrigation)

---

## 📚 Peta Konsep
```
FLUIDA & IRIGASI URBAN FARMING
│
├── 1. Tekanan Hidrostatis      → Tinggi tandon air menentukan tekanan
├── 2. Debit Air                → Berapa liter/menit yang mengalir ke tanaman
├── 3. Persamaan Kontinuitas    → Hubungan luas pipa dan kecepatan aliran
├── 4. Hukum Bernoulli          → Energi fluida dalam sistem pipa
└── 5. Proyek Mini              → Rancang sistem irigasi nyata
```

---
## 🔧 Persiapan: Jalankan Sel Ini Pertama!
"""

import numpy as np
import matplotlib.pyplot as plt
import ipywidgets as widgets
from IPython.display import display, HTML, clear_output
import warnings
warnings.filterwarnings('ignore')

display(HTML("""
<style>
.soal  { background:#e8f5e9; padding:12px; border-left:4px solid #2e7d32; border-radius:6px; margin:8px 0; }
.info  { background:#e3f2fd; padding:12px; border-left:4px solid #1565c0; border-radius:6px; margin:8px 0; }
.rumus { background:#fff8e1; padding:12px; border-left:4px solid #f9a825; border-radius:6px; margin:8px 0; }
.hasil { background:#f3e5f5; padding:12px; border-left:4px solid #6a1b9a; border-radius:6px; margin:8px 0; }
</style>
"""))
print('✅ Siap! Semua library berhasil dimuat. Selamat belajar!')

"""---
# BAB 1: Tekanan Hidrostatis
## 🏗️ Konteks: Tandon Air di Atap

Dalam urban farming, air ditampung di **tandon** yang diletakkan di ketinggian tertentu. Semakin tinggi tandon, semakin besar tekanan air yang mendorong aliran ke tanaman.

$$P = \rho \cdot g \cdot h$$

| Simbol | Besaran | Satuan |
|--------|---------|--------|
| $P$ | Tekanan hidrostatis | Pascal (Pa) |
| $\rho$ | Massa jenis fluida | kg/m³ |
| $g$ | Percepatan gravitasi | m/s² |
| $h$ | Ketinggian | meter (m) |
"""

display(HTML('<div class="info">🎮 <b>Simulasi Interaktif:</b> Geser slider untuk melihat pengaruh ketinggian tandon terhadap tekanan air.</div>'))

def simulasi_tekanan(h_tandon, rho):
    g = 9.8
    P = rho * g * h_tandon

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 5))
    fig.patch.set_facecolor('#f9fbe7')

    # Gambar sistem tandon
    ax1.set_xlim(0, 10)
    ax1.set_ylim(0, max(h_tandon + 3, 6))
    ax1.set_facecolor('#e8f5e9')
    ax1.set_title('Sistem Tandon Urban Farming', fontsize=13, fontweight='bold')
    ph = h_tandon - 0.5
    ax1.fill_between([2, 7], [ph]*2, [ph+0.3]*2, color='#795548', alpha=0.8)
    tandon = plt.Rectangle((3.5, ph+0.3), 2.5, 1.5, color='#1565c0', alpha=0.7)
    ax1.add_patch(tandon)
    ax1.text(4.75, ph+1.05, 'TANDON', ha='center', va='center', color='white', fontsize=9, fontweight='bold')
    air = plt.Rectangle((3.6, ph+0.4), 2.3, 1.0, color='#29b6f6', alpha=0.6)
    ax1.add_patch(air)
    ax1.fill_between([4.6, 5.1], [0.5]*2, [ph+0.3]*2, color='#78909c', alpha=0.8)
    ax1.fill_between([0, 10], [0]*2, [0.5]*2, color='#6d4c41', alpha=0.7)
    for x in [1.2, 2.5, 7.5, 8.8]:
        ax1.plot([x, x], [0.5, 1.3], color='#2e7d32', lw=2)
        ax1.plot([x-0.3, x+0.3], [1.0, 1.0], color='#43a047', lw=2)
    ax1.annotate('', xy=(6.5, ph+1.0), xytext=(6.5, 0.5), arrowprops=dict(arrowstyle='<->', color='red', lw=2))
    ax1.text(7.2, (ph+1.5)/2, f'h = {h_tandon} m', color='red', fontsize=11, fontweight='bold', va='center')
    ax1.set_xticks([]); ax1.set_ylabel('Ketinggian (m)')

    # Grafik P vs h
    h_range = np.linspace(0, 20, 200)
    P_range = rho * g * h_range / 1000
    ax2.plot(h_range, P_range, color='#1565c0', lw=2.5)
    ax2.axvline(x=h_tandon, color='red', linestyle='--', lw=2, label=f'h = {h_tandon} m')
    ax2.axhline(y=P/1000, color='green', linestyle='--', lw=2, label=f'P = {P/1000:.1f} kPa')
    ax2.scatter([h_tandon], [P/1000], color='red', s=100, zorder=5)
    ax2.fill_between(h_range, P_range, alpha=0.1, color='#1565c0')
    ax2.set_xlabel('Ketinggian tandon (m)', fontsize=11)
    ax2.set_ylabel('Tekanan hidrostatis (kPa)', fontsize=11)
    ax2.set_title('Grafik P vs h', fontsize=13, fontweight='bold')
    ax2.legend(fontsize=10); ax2.set_facecolor('#f3f9ff'); ax2.grid(True, alpha=0.3)
    plt.tight_layout(); plt.show()

    display(HTML(f'<div class="hasil"><b>📊 Hasil:</b> P = ρgh = {rho} × 9.8 × {h_tandon} = <b>{P:.1f} Pa = {P/1000:.2f} kPa</b></div>'))

w_h   = widgets.FloatSlider(value=5, min=1, max=20, step=0.5, description='Tinggi tandon (m):', style={'description_width':'150px'}, layout=widgets.Layout(width='480px'))
w_rho = widgets.Dropdown(options=[('Air murni (1000 kg/m³)',1000),('Air pupuk (1020 kg/m³)',1020)], value=1000, description='Jenis fluida:', style={'description_width':'150px'})
out1  = widgets.interactive_output(simulasi_tekanan, {'h_tandon': w_h, 'rho': w_rho})
display(widgets.VBox([w_h, w_rho]), out1)

"""---
### 📝 Latihan Soal 1
> Pak Budi memiliki tandon air di ketinggian **3 meter** di atas bedengan. Berapa tekanan hidrostatis yang mendorong air ke akar tanaman?
"""

# ✏️ LATIHAN SOAL 1 — Ganti ___ dengan nilai yang tepat
rho = 1000  # kg/m³
g   = 9.8   # m/s²
h   = ___   # ketinggian (meter)
P   = ___   # P = rho * g * h

print(f'Tekanan hidrostatis = {P} Pa = {P/1000:.2f} kPa')

if abs(P - 29400) < 100:
    display(HTML('<div class="soal">✅ <b>Benar!</b> P = 29.400 Pa ≈ 29,4 kPa. Hanya dari ketinggian 3 meter, air sudah terdorong dengan tekanan hampir 0,3 atmosfer!</div>'))
else:
    display(HTML('<div class="soal">❌ Belum tepat. Ingat rumus: P = ρ × g × h</div>'))

"""---
# BAB 2: Debit Air
## 💧 Konteks: Berapa Liter Air yang Dibutuhkan Tanaman?

**Debit** adalah volume air yang mengalir per satuan waktu:

$$Q = A \cdot v = \frac{V}{t}$$

| Simbol | Besaran | Satuan |
|--------|---------|--------|
| $Q$ | Debit | m³/s atau L/menit |
| $A$ | Luas penampang pipa | m² |
| $v$ | Kecepatan aliran | m/s |
| $V$ | Volume | liter |
| $t$ | Waktu | menit |
"""

display(HTML('<div class="info">🌿 <b>Kalkulator Debit Irigasi:</b> Hitung kebutuhan air dan durasi irigasi untuk kebunmu!</div>'))

def kalkulator_debit(d_pipa_mm, v_aliran, n_tanaman, kebutuhan_per_tanaman):
    d  = d_pipa_mm / 1000
    A  = np.pi * (d/2)**2
    Q_m3s = A * v_aliran
    Q_lmin = Q_m3s * 1000 * 60
    total  = n_tanaman * kebutuhan_per_tanaman
    waktu  = total / Q_lmin

    fig, axes = plt.subplots(1, 3, figsize=(14, 4))
    fig.patch.set_facecolor('#f1f8e9')

    # Penampang pipa
    theta = np.linspace(0, 2*np.pi, 300)
    r_vis = min(d_pipa_mm/50, 1.0)
    axes[0].fill(r_vis*np.cos(theta), r_vis*np.sin(theta), color='#29b6f6', alpha=0.5)
    axes[0].plot(r_vis*np.cos(theta), r_vis*np.sin(theta), color='#0277bd', lw=2)
    axes[0].set_aspect('equal')
    axes[0].set_title(f'Penampang Pipa\nØ {d_pipa_mm} mm', fontsize=11, fontweight='bold')
    axes[0].text(0, 0, f'A={A*1e4:.2f}\ncm²', ha='center', va='center', fontsize=10, fontweight='bold')
    axes[0].set_facecolor('#e3f2fd'); axes[0].set_xticks([]); axes[0].set_yticks([])

    # Bar chart
    bars = axes[1].bar(['Debit\n(L/menit)', 'Kebutuhan\n(L/hari)'], [Q_lmin, total], color=['#1565c0','#2e7d32'], alpha=0.8, width=0.5)
    for bar, val in zip(bars, [Q_lmin, total]):
        axes[1].text(bar.get_x()+bar.get_width()/2, bar.get_height()+max(Q_lmin,total)*0.02, f'{val:.1f}', ha='center', fontweight='bold', fontsize=11)
    axes[1].set_title('Debit vs Kebutuhan Air', fontsize=11, fontweight='bold')
    axes[1].set_facecolor('#f9fbe7'); axes[1].grid(True, alpha=0.3, axis='y')

    # Timeline
    t_range = np.linspace(0, waktu*1.2, 100)
    vol = np.minimum(Q_lmin * t_range, total)
    axes[2].plot(t_range, vol, color='#00796b', lw=2.5)
    axes[2].axhline(y=total, color='red', linestyle='--', lw=1.5, label=f'Target: {total:.0f} L')
    axes[2].axvline(x=waktu, color='orange', linestyle='--', lw=1.5, label=f'Selesai: {waktu:.1f} menit')
    axes[2].fill_between(t_range, vol, alpha=0.2, color='#00796b')
    axes[2].set_xlabel('Waktu (menit)'); axes[2].set_ylabel('Volume terpenuhi (L)')
    axes[2].set_title('Progres Irigasi', fontsize=11, fontweight='bold')
    axes[2].legend(fontsize=9); axes[2].set_facecolor('#e0f2f1'); axes[2].grid(True, alpha=0.3)
    plt.tight_layout(); plt.show()

    display(HTML(f'<div class="hasil"><b>📊 Hasil:</b> Q = {Q_lmin:.2f} L/menit &nbsp;|&nbsp; Total air = {total:.0f} L/hari &nbsp;|&nbsp; <b>Durasi irigasi = {waktu:.1f} menit/hari</b></div>'))

w_d = widgets.IntSlider(value=20, min=5, max=50, step=5, description='Diameter pipa (mm):', style={'description_width':'160px'}, layout=widgets.Layout(width='480px'))
w_v = widgets.FloatSlider(value=0.5, min=0.1, max=3.0, step=0.1, description='Kec. aliran (m/s):', style={'description_width':'160px'}, layout=widgets.Layout(width='480px'))
w_n = widgets.IntSlider(value=20, min=5, max=100, step=5, description='Jumlah tanaman:', style={'description_width':'160px'}, layout=widgets.Layout(width='480px'))
w_k = widgets.FloatSlider(value=0.5, min=0.1, max=2.0, step=0.1, description='Kebutuhan (L/hari):', style={'description_width':'160px'}, layout=widgets.Layout(width='480px'))
out2 = widgets.interactive_output(kalkulator_debit, {'d_pipa_mm':w_d,'v_aliran':w_v,'n_tanaman':w_n,'kebutuhan_per_tanaman':w_k})
display(widgets.VBox([w_d, w_v, w_n, w_k]), out2)

"""---
# BAB 3: Persamaan Kontinuitas
## 🔀 Konteks: Pipa Utama ke Selang Tetes

Sistem irigasi menggunakan pipa utama yang bercabang ke selang-selang tetes yang lebih kecil.

$$A_1 \cdot v_1 = A_2 \cdot v_2$$

> Ketika pipa menyempit, kecepatan aliran **meningkat** agar debit tetap konstan.
"""

display(HTML('<div class="info">🔀 <b>Simulasi Kontinuitas:</b> Lihat bagaimana kecepatan berubah saat pipa menyempit.</div>'))

def simulasi_kontinuitas(d1_mm, v1, d2_mm):
    A1 = np.pi*(d1_mm/2000)**2
    A2 = np.pi*(d2_mm/2000)**2
    v2 = A1*v1/A2

    fig, ax = plt.subplots(figsize=(12, 4))
    ax.set_xlim(0,12); ax.set_ylim(0,4); ax.set_facecolor('#e8f5e9')
    ax.set_title('Persamaan Kontinuitas: Pipa Utama → Selang Tetes', fontsize=13, fontweight='bold')

    r1 = min(d1_mm/40, 1.2); r2 = min(d2_mm/40, 0.8)
    cx = 2.0
    ax.fill_between([0,5],[cx-r1]*2,[cx+r1]*2,color='#78909c',alpha=0.4)
    ax.fill_between([0,5],[cx-r1+0.05]*2,[cx+r1-0.05]*2,color='#29b6f6',alpha=0.4)
    ax.fill([5,5,6,6],[cx-r1,cx+r1,cx+r2,cx-r2],color='#78909c',alpha=0.4)
    ax.fill_between([6,11],[cx-r2]*2,[cx+r2]*2,color='#78909c',alpha=0.4)
    ax.fill_between([6,11],[cx-r2+0.03]*2,[cx+r2-0.03]*2,color='#29b6f6',alpha=0.5)

    for x in np.linspace(0.5, 4.2, 4):
        ax.annotate('', xy=(x+0.7,cx), xytext=(x,cx), arrowprops=dict(arrowstyle='->',color='#0d47a1',lw=1.8))
    n2 = min(int(v2/v1*4)+2, 7)
    for x in np.linspace(6.5, 10.0, n2):
        ax.annotate('', xy=(x+0.45,cx), xytext=(x,cx), arrowprops=dict(arrowstyle='->',color='#b71c1c',lw=1.8))

    ax.text(2.5, cx+r1+0.2, f'Ø{d1_mm}mm  v₁={v1:.1f}m/s', ha='center', fontsize=10, color='#1565c0', fontweight='bold')
    ax.text(8.5, cx+r2+0.2, f'Ø{d2_mm}mm  v₂={v2:.2f}m/s', ha='center', fontsize=10, color='#b71c1c', fontweight='bold')
    ax.text(5.5, 0.4, f'A₁v₁ = A₂v₂  →  kecepatan naik {v2/v1:.1f}×', ha='center', fontsize=10,
           bbox=dict(boxstyle='round', facecolor='#fff8e1', edgecolor='#f9a825'))
    ax.set_xticks([]); ax.set_yticks([])
    plt.tight_layout(); plt.show()

    display(HTML(f'<div class="hasil"><b>📊 Hasil:</b> v₁={v1:.1f} m/s → v₂=<b>{v2:.2f} m/s</b> &nbsp;|&nbsp; Debit Q = {A1*v1*1e6:.2f} cm³/s (konstan)</div>'))

w_d1 = widgets.IntSlider(value=25,min=10,max=50,step=5,description='Ø pipa utama (mm):',style={'description_width':'180px'},layout=widgets.Layout(width='480px'))
w_v1 = widgets.FloatSlider(value=0.5,min=0.1,max=2.0,step=0.1,description='Kec. pipa utama (m/s):',style={'description_width':'180px'},layout=widgets.Layout(width='480px'))
w_d2 = widgets.IntSlider(value=8,min=2,max=20,step=1,description='Ø selang tetes (mm):',style={'description_width':'180px'},layout=widgets.Layout(width='480px'))
out3 = widgets.interactive_output(simulasi_kontinuitas,{'d1_mm':w_d1,'v1':w_v1,'d2_mm':w_d2})
display(widgets.VBox([w_d1,w_v1,w_d2]),out3)

"""---
# BAB 4: Hukum Bernoulli
## ⚡ Konteks: Energi Air dalam Sistem Pipa Irigasi

$$P_1 + \frac{1}{2}\rho v_1^2 + \rho g h_1 = P_2 + \frac{1}{2}\rho v_2^2 + \rho g h_2$$

| Komponen | Nama |
|----------|------|
| $P$ | Energi tekanan |
| $\frac{1}{2}\rho v^2$ | Energi kinetik per volume |
| $\rho g h$ | Energi potensial per volume |
"""

display(HTML('<div class="info">⚡ <b>Simulasi Bernoulli:</b> Hitung tekanan di titik keluaran irigasi.</div>'))

def simulasi_bernoulli(h1, v1, h2, d1_mm, d2_mm):
    rho=1000; g=9.8; P1=101325
    A1=np.pi*(d1_mm/2000)**2; A2=np.pi*(d2_mm/2000)**2
    v2=A1*v1/A2
    P2=P1+0.5*rho*v1**2+rho*g*h1-0.5*rho*v2**2-rho*g*h2

    fig,(ax1,ax2)=plt.subplots(1,2,figsize=(13,5))
    fig.patch.set_facecolor('#f9fbe7')

    ax1.set_xlim(0,10); ax1.set_ylim(0,max(h1,h2)+3); ax1.set_facecolor('#e8f5e9')
    ax1.set_title('Sistem Pipa Irigasi Bertingkat',fontsize=12,fontweight='bold')
    tandon=plt.Rectangle((0.5,h1-0.5),2,1.5,color='#1565c0',alpha=0.7); ax1.add_patch(tandon)
    ax1.text(1.5,h1+0.25,'Titik 1\n(Tandon)',ha='center',va='center',color='white',fontsize=8,fontweight='bold')
    ax1.annotate('',xy=(7.5,h2+0.3),xytext=(2.5,h1+0.2),arrowprops=dict(arrowstyle='->',color='#0277bd',lw=3))
    ax1.fill_between([7,9],[h2]*2,[h2+0.6]*2,color='#4caf50',alpha=0.6)
    ax1.text(8,h2+0.3,'Titik 2\n(Keluaran)',ha='center',va='center',fontsize=8,fontweight='bold')
    ax1.fill_between([0,10],[0]*2,[0.3]*2,color='#6d4c41',alpha=0.7)
    ax1.annotate('',xy=(9.5,h1),xytext=(9.5,0),arrowprops=dict(arrowstyle='<->',color='red',lw=1.5))
    ax1.text(9.7,h1/2,f'h₁={h1}m',color='red',fontsize=9,va='center')
    ax1.annotate('',xy=(0.2,h2),xytext=(0.2,0),arrowprops=dict(arrowstyle='<->',color='blue',lw=1.5))
    ax1.text(0.4,h2/2,f'h₂={h2}m',color='blue',fontsize=9,va='center')
    ax1.set_xticks([])

    labels=['Titik 1\n(Tandon)','Titik 2\n(Keluaran)']
    x=np.arange(2); w=0.25
    ax2.bar(x-w,[P1/1000,max(P2/1000,0)],w,label='Tekanan',color='#1565c0',alpha=0.8)
    ax2.bar(x,[0.5*rho*v1**2/1000,0.5*rho*v2**2/1000],w,label='Kinetik',color='#e53935',alpha=0.8)
    ax2.bar(x+w,[rho*g*h1/1000,rho*g*h2/1000],w,label='Potensial',color='#2e7d32',alpha=0.8)
    ax2.set_xticks(x); ax2.set_xticklabels(labels)
    ax2.set_ylabel('Energi per volume (kPa)'); ax2.set_title('Distribusi Energi Bernoulli',fontsize=12,fontweight='bold')
    ax2.legend(fontsize=9); ax2.set_facecolor('#f3f9ff'); ax2.grid(True,alpha=0.3,axis='y')
    plt.tight_layout(); plt.show()

    status='✅ Tekanan positif — air mengalir dengan baik!' if P2>0 else '⚠️ Tekanan negatif — naikkan ketinggian tandon!'
    display(HTML(f'<div class="hasil"><b>📊 Hasil Bernoulli:</b> P₂ = <b>{P2/1000:.2f} kPa</b> &nbsp;|&nbsp; v₂ = {v2:.2f} m/s<br>{status}</div>'))

w_h1=widgets.FloatSlider(value=8,min=2,max=20,step=0.5,description='Tinggi tandon h₁ (m):',style={'description_width':'180px'},layout=widgets.Layout(width='480px'))
w_v1b=widgets.FloatSlider(value=0.3,min=0.1,max=2.0,step=0.1,description='Kec. tandon v₁ (m/s):',style={'description_width':'180px'},layout=widgets.Layout(width='480px'))
w_h2=widgets.FloatSlider(value=1,min=0,max=10,step=0.5,description='Tinggi keluaran h₂ (m):',style={'description_width':'180px'},layout=widgets.Layout(width='480px'))
w_d1b=widgets.IntSlider(value=25,min=10,max=50,step=5,description='Ø pipa utama (mm):',style={'description_width':'180px'},layout=widgets.Layout(width='480px'))
w_d2b=widgets.IntSlider(value=8,min=2,max=20,step=1,description='Ø keluaran (mm):',style={'description_width':'180px'},layout=widgets.Layout(width='480px'))
out4=widgets.interactive_output(simulasi_bernoulli,{'h1':w_h1,'v1':w_v1b,'h2':w_h2,'d1_mm':w_d1b,'d2_mm':w_d2b})
display(widgets.VBox([w_h1,w_v1b,w_h2,w_d1b,w_d2b]),out4)

"""---
# BAB 5: 🏗️ Proyek Mini — Rancang Sistem Irigasi!

> Kamu adalah insinyur urban farming yang merancang sistem irigasi untuk rooftop garden sebuah sekolah di **Palembang**.
>
> **Spesifikasi:**
> - 50 tanaman sayuran
> - Kebutuhan air: 0,8 liter/tanaman/hari
> - Tandon di ketinggian 6 meter
> - Pipa utama: Ø 25 mm
> - Selang tetes: Ø 5 mm

**Lengkapi kode di bawah (ganti `___` dengan rumus yang tepat):**
"""

import numpy as np

# DATA YANG DIKETAHUI
rho=1000; g=9.8; h=6; n_tanaman=50; kebutuhan=0.8; d1_mm=25; d2_mm=5

# TUGAS 1: Tekanan hidrostatis
P = rho * g * h  # P = rho * g * h

# TUGAS 2: Luas penampang pipa
A1 = np.pi * (d1_mm/2000)**2  # np.pi * (d1_mm/2000)**2
A2 = np.pi * (d2_mm/2000)**2  # np.pi * (d2_mm/2000)**2

# TUGAS 3: Kecepatan aliran (pendekatan Torricelli)
v1 = np.sqrt(2*g*h) * 0.6  # sudah diberikan, faktor 0.6 = koreksi gesekan pipa
v2 = A1*v1/A2  # persamaan kontinuitas: A1*v1/A2

# TUGAS 4: Debit dan waktu irigasi
Q_lmin = A1 * v1 * 1000 * 60  # A1 * v1 * 1000 * 60  (konversi ke liter/menit)
total_air = n_tanaman * kebutuhan
waktu = total_air / Q_lmin   # total_air / Q_lmin

print('='*50)
print('   LAPORAN RANCANGAN SISTEM IRIGASI')
print('   Rooftop Garden — Palembang')
print('='*50)
print(f'Tekanan hidrostatis  : {P:.0f} Pa = {P/1000:.1f} kPa')
print(f'Kecepatan pipa utama : {v1:.2f} m/s')
print(f'Kecepatan selang tetes:{v2:.2f} m/s')
print(f'Debit air            : {Q_lmin:.2f} liter/menit')
print(f'Total kebutuhan air  : {total_air:.0f} liter/hari')
print(f'Durasi irigasi/hari  : {waktu:.1f} menit')
print('='*50)
if waktu < 30:   print('✅ EFISIEN: Irigasi selesai dalam < 30 menit!')
elif waktu < 60: print('✅ CUKUP: Durasi irigasi wajar.')
else:            print('⚠️ Pertimbangkan pipa berdiameter lebih besar.')

"""---
# 📋 Rangkuman

| Konsep | Rumus | Aplikasi Urban Farming |
|--------|-------|------------------------|
| Tekanan hidrostatis | $P = \rho g h$ | Menentukan ketinggian tandon |
| Debit air | $Q = Av = V/t$ | Menghitung waktu irigasi |
| Persamaan Kontinuitas | $A_1v_1 = A_2v_2$ | Memilih diameter pipa |
| Hukum Bernoulli | $P+\frac{1}{2}\rho v^2+\rho gh = \text{konstan}$ | Menganalisis energi sistem pipa |

---
## 🌱 Refleksi
Jawab di sel markdown ini (klik dua kali untuk edit):

1. Mengapa tandon air sebaiknya diletakkan setinggi mungkin?
2. Apa yang terjadi pada kecepatan air jika selang tetes lebih kecil?
3. Bagaimana Bernoulli membantu merancang irigasi yang hemat energi?

*✏️ Jawaban kamu di sini...*

---
**E-Modul Fisika: Fluida & Irigasi Urban Farming**  
*SMA — Kurikulum Merdeka | Program Studi Magister Pendidikan Fisika, FKIP Universitas Sriwijaya*
"""